version: "3.8"

services:
  app:
    build:
      context: .
    container_name: portal-booking-app
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: portal-booking-nginx
    ports:
      - "8000:80"
    volumes:
      - ./portal-booking:/var/www/portal-booking
      - ./portal-booking/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:14
    container_name: portal-booking-db
    environment:
      POSTGRES_DB: portal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
# made by Rifky Setya Rahman